name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      SHELL: /bin/bash
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.2

    - name: Build
      run: go build -v ./...

    - name: Install
      run: make install

    - name: Test
      run: termbacktime --version
